INSERT INTO regions (region_name)
VALUES  ('Spain'),
        ('Portugal'),
        ('France'),
        ('Germany'),
        ('Poland'),
        ('Austria'),
        ('Bulgaria'),
        ('Greece'),
        ('Italy'),
        ('Hungary'),
        ('United Kingdom'),
        ('South Africa'),
        ('New Zealand'),
        ('Australia'),
        ('Argentina'),
        ('Chile'),
        ('Brazil'),
        ('Canada'),
        ('Mexico'),
        ('California'),
        ('Oregon'),
        ('Washington'),
        ('China');



INSERT INTO grapes (grape_name)
VALUES  ('Cabernet Sauvignon'),
        ('Syrah'),
        ('Cabernet Franc'),
        ('Grenache'),
        ('Schiava'),
        ('Rondo'),
        ('Regent'),
        ('Lagrein'),
        ('Chambourcin'),
        ('Merlot'),
        ('Pinot Noir'),
        ('Pinot Grigio'),
        ('Sauvignon Blanc'),
        ('Chardonnay'),
        ('Riesling'),
        ('Bacchus'),
        ('Chasselas'),
        ('Solaris'),
        ('Malbec'),
        ('Zinfandel'),
        ('Gewurztraminer'),
        ('Gamay Noir'),
        ('Nero d''Avola'),
        ('Carignan');

INSERT INTO colors (color_name)
VALUES  ('red'),
        ('white'),
        ('rose'),
        ('orange');
